export const defaultUserData = {
  name: '',
  email: '',
  birthday: '01.01.2000',
  hobby: '',
  season: '',
  flower: '',
  dish: '',
  chillTime: '',
  film: '',
  singer: '',
  color: '',
  positiveTraits: '',
  dream: '',
};
