export {default as HomePage} from './HomePage'
export {default as AuthPage} from './AuthPage'
export {default as NotFoundPage} from './NotFoundPage'
export {default as PersonPage} from './PersonPage'
export {default as AboutPage} from './AboutPage'
export {default as AccountPage} from './AccountPage'
export {default as CatalogPage} from './CatalogPage'
export {default as CatPage} from './CatPage'