export { AboutPage } from './about/AboutPage';
export { AccountPage } from './account/AccountPage';
export { CatPage } from './cat/CatPage';
export { CatalogPage } from './catalog/CatalogPage';
export { HomePage } from './home/HomePage';
export { NotFoundPage } from './not-found/NotFoundPage';
export { PersonPage } from './person/PersonPage';
export { AuthorizationPage } from './auth&reg/authorization/AuthorizationPage';
export { RegistrationPage } from './auth&reg/registration/RegistrationPage';
